### ISSUE TITLE
adoc links to raw format which is illegible - link to the repo instead

### ISSUE THREAD

**Issue by mub** [spring-guides/gs-spring-boot#48]
The provided links to the `getting-started-macros` repo point to the raw format which is unformatted plain text. Link like this instead:

```
https://github.com/spring-guides/getting-started-macros/blob/master/prereq_editor_jdk_buildtools.adoc
```

&uarr; that would provide a [&rarr;formatted view](https://github.com/spring-guides/getting-started-macros/blob/master/prereq_editor_jdk_buildtools.adoc).

**Comment by gregturn** [comment]
Again this content is served up on spring.io.

**Comment by mub** [comment]
@gregturn the links are:

`https://raw.githubusercontent.com/...` :larr; that's `spring.io` :question:

**Comment by gregturn** [comment]
This entire guide is pulled into Spring.io and through an embedded instance of asciidoctor to render it there. We need the raw version of adoc fragment to properly produce output. 

Side effect: doesn’t look at nice here on GitHub.

**Comment by gregturn** [comment]
Essentially, I would get this at the bottom:

![screen shot 2018-06-07 at 12 03 08 pm](https://user-images.githubusercontent.com/311040/41114705-ce0818c2-6a4a-11e8-8aac-ef8de28a6e8c.png)

Instead of this:

![screen shot 2018-06-07 at 12 04 03 pm](https://user-images.githubusercontent.com/311040/41114742-e73d4060-6a4a-11e8-8af8-22e1c59d2b01.png)
